eTickets/Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allActors = await _service.GetAllAsync();
            return View(allActors.OrderBy(x => x.FullName));
        }

        // Get: Actors/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // Post: Create
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("FullName, ProfilePictureUrl, Bio")]Actor actor)
        {
            if(!ModelState.IsValid) 
            {
                return View(actor);
            }

            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null)
                return View("NotFound");
            return View(actorDetails);
        }

        // Get: Actors/Edit/1
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null)
                return View("NotFound");
            return View(actorDetails);
        }

        // Post: Edit
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit([Bind("Id, FullName, ProfilePictureUrl, Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            await _service.UpdateAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        // Get: Actors/Delete/1
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null)
                return View("NotFound");
            return View(actorDetails);
        }

        // Post: DeleteConfirmed
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);

            if (actorDetails == null)
                return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;

        public CinemasController(ICinemasService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var allCinemas = await _service.GetAllAsync();
            return View(allCinemas.OrderBy(x => x.Name));
        }

        // Get: Cinemas/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // Post: Create
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("Name, Logo, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }

            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        //Get: Cinemas/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);

            if (cinemaDetails == null)
                return View("NotFound");
            return View(cinemaDetails);
        }

        // Get: Cinemas/Edit/1
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);

            if (cinemaDetails == null)
                return View("NotFound");
            return View(cinemaDetails);
        }

        // Post: Edit
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit([Bind("Id, Name, Logo, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }

            await _service.UpdateAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        // Get: Cinema/Delete/1
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);

            if (cinemaDetails == null)
                return View("NotFound");
            return View(cinemaDetails);
        }

        // Post: DeleteConfirmed
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);

            if (cinemaDetails == null)
                return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;

        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allMovies = await _service.GetAllAsync(x => x.Cinema);
            return View(allMovies.OrderByDescending(d => d.StartDate));
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovies = await _service.GetAllAsync(x => x.Cinema);

            if (!string.IsNullOrEmpty(searchString))
            {
                var filteredResults = allMovies.Where(n => n.Name.Contains(searchString)
                                        || n.Description.Contains(searchString)).ToList();
                return View("Index", filteredResults);
            }

            return View("Index", allMovies.OrderByDescending(d => d.StartDate));
        }

        // GET: Movies/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id);
            if (movieDetail == null)
                return View("NotFound");
            return View(movieDetail);
        }

        // Get: Movies/Create
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Directors = new SelectList(movieDropdownsData.Directors, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();
        }

        // Post: Movies/Create
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create(NewMovieVM movie) 
        {
            if(!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Directors = new SelectList(movieDropdownsData.Directors, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        // Get: Movies/Edit/1
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if (movieDetails == null)
                return View("NotFound");

            var response = new NewMovieVM
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                ImageUrl = movieDetails.ImageUrl,
                MovieCategory = movieDetails.MovieCategory,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                CinemaId = movieDetails.CinemaId,
                DirectorId = movieDetails.DirectorId,
                ActorIds = movieDetails.Actors_Movies.Select(a => a.ActorId).ToList()
            };

            // We need data in dropdowns
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Directors = new SelectList(movieDropdownsData.Directors, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(response);
        }

        // Post: Movies/Edit
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (id != movie.Id)
                return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Directors = new SelectList(movieDropdownsData.Directors, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        // Get: Movies/Delete/1
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if (movieDetails == null)
                return View("NotFound");
            return View(movieDetails);
        }

        // Post: DeleteConfirmed
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if (movieDetails == null)
                return View("NotFound");

            await _service.DeleteMovieAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTickets/Controllers/OrdersController.cs
using eTickets.Data.Cart;
using eTickets.Data.Services;
using eTickets.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var movie = await _moviesService.GetMovieByIdAsync(id);

            if(movie != null)
            {
                _shoppingCart.AddItemToCart(movie);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var movie = await _moviesService.GetMovieByIdAsync(id);

            if (movie != null)
            {
                _shoppingCart.RemoveItemFromCart(movie);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmail = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmail);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }
    }
}

eTickets/Views/Shared/AccessDenied.cshtml
<div class="message--gradient">
    <div class="message__container message__container--gradient">
        <h1 class="heading-secondary message__title--gradient">
            Access Denied
        </h1>
        <p class="message__comment">Please, click the button below to be redirected to the home page.</p>
        <a asp-controller="Movies" asp-action="Index" class="btn btn--medium btn--rectangle btn--white">
            Main Page
        </a>
    </div>
</div>

eTickets/Views/Shared/NotFound.cshtml
<div class="message">
    <div class="message__container">
        <h1 class="heading-secondary message__title text-red">The page was not found:(</h1>
        <div class="message__btns">
            <a asp-controller="Movies" asp-action="Index"
               class="btn btn--medium btn--rectangle btn--secondary details__btn">
                Go to main page
            </a>
        </div>
    </div>
</div>

eTickets/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
    <a asp-controller="@Model" asp-action="Create"
       class="btn btn--rectangle btn--secondary btn--big list__add">
        <svg>
            <use xlink:href="/img/sprite.svg#icon-plus"></use>
        </svg>
        Add new
    </a>
}

eTickets/Views/Shared/_Identity.cshtml
@if (User.Identity.IsAuthenticated)
{
    @*Display User Profile DropDown*@
    <div class="header__nav-item--dropdown header__btn--2">
        <a href="#" class="btn btn--rectangle btn--primary btn--standard btn--dropdown">
            <svg>
                <use xlink:href="/img/sprite.svg#icon-happy"></use>
            </svg>
            Account
            <svg class="header__nav-icon header__nav-icon--toggle">
                <use xlink:href="/img/sprite.svg#icon-triangle-down"></use>
            </svg>
        </a>
        <div class="header__nav-dropdown-content">
            <a href="#" class="header__nav-link header__nav-link--dropdown">
                <svg class="header__nav-icon header__nav-icon--dropdown">
                    <use xlink:href="/img/sprite.svg#icon-user"></use>
                </svg>
                <span>Profile</span>
            </a>
            <a asp-controller="Orders" asp-action="Index" class="header__nav-link header__nav-link--dropdown">
                <svg class="header__nav-icon header__nav-icon--dropdown">
                    <use xlink:href="/img/sprite.svg#icon-ticket"></use>
                </svg>
                <span>Orders</span>
            </a>
            @if (User.IsInRole("admin"))
            {
                <a asp-controller="Account" asp-action="Users" class="header__nav-link header__nav-link--dropdown">
                    <svg class="header__nav-icon header__nav-icon--dropdown">
                        <use xlink:href="/img/sprite.svg#icon-users"></use>
                    </svg>
                    <span>Users</span>
                </a>
            }
        </div>
    </div>

    @*Display Log Out Button*@
    <form asp-controller="Account" asp-action="Logout" class="header__btn--3">
        <button class="btn btn--rectangle btn--primary btn--standard">
            <svg>
                <use xlink:href="/img/sprite.svg#icon-log-out"></use>
            </svg>
            Log Out
        </button>
    </form>
}
else
{
    @*Display Log In Button*@
    <a asp-controller="Account" asp-action="Login"
       class="btn btn--rectangle btn--primary btn--standard header__btn--2">
        <svg>
            <use xlink:href="/img/sprite.svg#icon-login"></use>
        </svg>
        Log In
    </a>

    @*Display Register Button*@
    <a asp-controller="Account" asp-action="Register"
       class="btn btn--rectangle btn--primary btn--standard header__btn--3">
        <svg>
            <use xlink:href="/img/sprite.svg#icon-add-user"></use>
        </svg>
        Register
    </a>
}

eTickets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="shortcut icon" type="image/png" href="/img/favicon.png" />
    <title>@ViewData["Title"] - eTickets</title>
</head>
<body>
    <header class="header">
        <a class="header__logo" asp-area="" asp-controller="Movies" asp-action="Index">
            <svg class="header__logo-icon">
                <use xlink:href="/img/sprite.svg#icon-ticket"></use>
            </svg>
            <span class="header__logo-text">eTicket</span>
        </a>

        <div class="header__nav">
            <ul class="header__nav-list">
                <li class="header__nav-item">
                    <a class="header__nav-link header__nav-link--secondary" asp-area="" asp-controller="Movies" asp-action="Index">
                        <svg class="header__nav-icon">
                            <use href="/img/sprite.svg#icon-video"></use>
                        </svg>
                        <span>Movies</span>
                    </a>
                </li>
                @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                {
                    <li class="header__nav-item header__nav-item--dropdown">
                        <a href="#" class="header__nav-link header__nav-link--secondary">
                            <svg class="header__nav-icon">
                                <use xlink:href="/img/sprite.svg#icon-cog"></use>
                            </svg>
                            <span>Management</span>
                            <svg class="header__nav-icon header__nav-icon--toggle">
                                <use xlink:href="/img/sprite.svg#icon-triangle-down"></use>
                            </svg>
                        </a>
                        <div class="header__nav-dropdown-content">
                            <a class="header__nav-link header__nav-link--dropdown" asp-controller="Cinemas" asp-action="Index">
                                <svg class="header__nav-icon header__nav-icon--dropdown">
                                    <use xlink:href="/img/sprite.svg#icon-video-camera"></use>
                                </svg>
                                <span>Cinemas</span>
                            </a>
                            <a class="header__nav-link header__nav-link--dropdown" asp-controller="Directors" asp-action="Index">
                                <svg class="header__nav-icon header__nav-icon--dropdown">
                                    <use xlink:href="/img/sprite.svg#icon-bullhorn"></use>
                                </svg>
                                <span>Directors</span>
                            </a>
                            <a class="header__nav-link header__nav-link--dropdown" asp-controller="Actors" asp-action="Index">
                                <svg class="header__nav-icon header__nav-icon--dropdown">
                                    <use xlink:href="/img/sprite.svg#icon-mask"></use>
                                </svg>
                                <span>Actors</span>
                            </a>
                        </div>
                    </li>
                }
            </ul>
        </div>

        <form asp-controller="Movies" asp-action="Filter" class="header__search">
            <input type="text"
                   name="searchString"
                   class="header__search-input"
                   placeholder="Search for the movie..." />
            <button type="submit" class="header__search-btn">
                <svg class="header__search-icon">
                    <use xlink:href="/img/sprite.svg#icon-magnifying-glass"></use>
                </svg>
            </button>
        </form>

        @await Component.InvokeAsync("ShoppingCartSummary")

       <partial name="_Identity.cshtml" />
        
    </header>

    <main>
        @RenderBody()
    </main>

    <footer class="footer">
        <p class="footer__text">
            This Website was NOT created for commercial use, but only for practicing
            programming skills. All movie titles, pictures, etc... are registered
            trademarks and/or copyrights of their respective holders.
        </p>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>